config/routes.rb
Rails.application.routes.draw do
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider
  root 'static_pages#top'
  get 'static_pages/term'
  get 'static_pages/privacy'
  namespace :admin do
    root 'static_pages#top'
    resources :armors, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :users, only: [:destroy]
    resources :posts, only: [:destroy]
  end
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :mypages, only: [:index]
    resources :favorites, only: [:index]
  end
  resources :posts, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  resources :contacts, only: [:new, :create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  resources :password_resets, only: [:new, :create, :edit, :update]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arm_armor.rb
class ArmArmor < Armor
end

app/models/armor.rb
class Armor < ApplicationRecord
  has_many :posts

  validates :type, presence: true
  validates :name, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: true }
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/body_armor.rb
class BodyArmor < Armor
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/first_color.rb
class FirstColor < ApplicationRecord
  belongs_to :post, optional: true

  enum part: { head: 0, body: 1, arm: 2, waist: 3, foot: 4 }

  validates :hue, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 360 }
  validates :saturation, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  validates :value, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
end

app/models/foot_armor.rb
class FootArmor < Armor
end

app/models/head_armor.rb
class HeadArmor < Armor
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :first_colors, dependent: :destroy
  has_many :second_colors, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  accepts_nested_attributes_for :first_colors, :second_colors

  belongs_to :user
  belongs_to :head_armor, optional: true
  belongs_to :body_armor, optional: true
  belongs_to :arm_armor, optional: true
  belongs_to :waist_armor, optional: true
  belongs_to :foot_armor, optional: true

  validates :character_gender, presence: true
  # imageカラムのバリデーションをカスタムする
  # エラーメッセージの内容を変更したい(今のままでは不自然)
  validates :image, presence: true

  enum character_gender: { gentlemen: 0, lady: 1 }

  def armor_name(object)
    if object.nil?
      'なし'
    else
      object.name
    end
  end

  def armors
    [head_armor, body_armor, arm_armor, waist_armor, foot_armor]
  end

  # postが保存されると、colorsのpartにそれぞれ値をいれる
  def first_color_change_part
    first_colors.first.update(part: 'head')
    first_colors.second.update(part: 'body')
    first_colors.third.update(part: 'arm')
    first_colors.fourth.update(part: 'waist')
    first_colors.fifth.update(part: 'foot')
  end

  def second_color_change_part
    second_colors.first.update(part: 'head')
    second_colors.second.update(part: 'body')
    second_colors.third.update(part: 'arm')
    second_colors.fourth.update(part: 'waist')
    second_colors.fifth.update(part: 'foot')
  end

  # いいねの多い順で並び替える
  ransacker :likes_count do
    query = '(SELECT COUNT(likes.post_id) FROM likes where likes.post_id = posts.id GROUP BY likes.post_id)'
    Arel.sql(query)
  end

  # partを指定して、first_colorsを生成
  # def first_colors_build_specify_parts
  #   first_colors.build(part: 'head')
  #   first_colors.build(part: 'body')
  #   first_colors.build(part: 'arm')
  #   first_colors.build(part: 'waist')
  #   first_colors.build(part: 'foot')
  # end

  # partを指定して、second_colorsを生成
  # def second_colors_build_specify_parts
  #   second_colors.build(part: 'head')
  #   second_colors.build(part: 'body')
  #   second_colors.build(part: 'arm')
  #   second_colors.build(part: 'waist')
  #   second_colors.build(part: 'foot')
  # end
end

app/models/second_color.rb
class SecondColor < ApplicationRecord
  belongs_to :post, optional: true

  enum part: { head: 0, body: 1, arm: 2, waist: 3, foot: 4 }

  validates :hue, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 360 }
  validates :saturation, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  validates :value, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, uniqueness: true, allow_nil: true

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  enum role: { general: 0, admin: 1 }

  def own?(object)
    id == object.user_id
  end

  def like?(post)
    likes.where(post_id: post.id).exists?
  end
end

app/models/waist_armor.rb
class WaistArmor < Armor
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::BaseController
    before_action :set_user, only: [:destroy]

    def destroy
      @user.destroy!
      redirect_to admin_user_path, success: (t '.success')
    end

    private

    def set_user
      @user = User.find(params[:id])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: (t '.success')
    else
      # 新規登録に失敗すると、urlが/usersになってしまう
      # redirect_toを使用するなら、flashにエラーメッセージを入れる？
      flash.now[:danger] = t '.fail'
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), success: (t '.success')
    else
      flash.now[:fail] = t '.fail'
      render :edit
    end
  end

  def destroy
    @user.destroy!
    redirect_to new_user_path, success: (t '.success')
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def authenticate_user
    user = User.find(params[:id])
    redirect_to root_path unless current_user && current_user == user
  end
end

app/helpers/admin/users_helper.rb
module Admin
  module UsersHelper
  end
end

app/helpers/armors_helper.rb
module ArmorsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
= form_with model: user, local: true do |f|

  = render 'shared/error_message', object: f.object

  .text-center.mb-3.mt-3
    = link_to auth_at_provider_path(provider: :twitter) do
      i.fab.fa-twitter style='color: #3399FF;'
      | Twitterでログイン
  .mx-auto
    .field
      = f.label :name, class: 'col-md-12'
      = f.text_field :name, class: 'form-field'

    .field
      = f.label :email, class: 'col-md-12'
      = f.email_field :email, class: 'form-field'

    .field
      = f.label :password, class: 'col-md-12'
      = f.password_field :password, class: 'password-field'

    .field
      = f.label :password_confirmation, class: 'col-md-12'
      = f.password_field :password_confirmation, class: 'password-field'
    
    .actions.text-center
      = f.submit button_name

app/views/users/edit.html.slim
- provide :title, (t '.title')

h3.text-center.mb-3
  = t '.title'

= render 'form', user: @user, button_name: (t 'defaults.update')

/ = form_with model: @user, local: true do |f|

/   = render 'shared/error_message', object: f.object

/   .field
/     = f.label :name
/     = f.text_field :name

/   .field
/     = f.label :email
/     = f.email_field :email

/   .field
/     = f.label :password
/     = f.password_field :password

/   .field
/     = f.label :password_confirmation
/     = f.password_field :password_confirmation

/   .actions
/     = f.submit t 'defaults.update'

app/views/users/new.html.slim
- provide :title, (t '.title')

h3.text-center
  = t '.title'

= render 'form', user: @user, button_name: (t 'defaults.register')

app/views/users/show.html.slim
- provide :title, (t '.title')

h3.text-center.mb-3
  = t '.title'

table.user-show
  thead
    tr
      th
        = User.human_attribute_name(:name)
      th
        = User.human_attribute_name(:email)

  tbody
    tr
      td
        = current_user.name
      td
        = current_user.email
      td
        = link_to '編集', edit_user_path(current_user), class: 'edit-link'
      td
        = link_to '削除', user_path(current_user), method: :delete, data: { confirm: (t '.dialog') }, class: 'destroy-link' unless current_user.admin? 