config/routes.rb
Rails.application.routes.draw do
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider
  root 'static_pages#top'
  get 'static_pages/term'
  get 'static_pages/privacy'
  namespace :admin do
    root 'static_pages#top'
    resources :armors, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :users, only: [:destroy]
    resources :posts, only: [:destroy]
  end
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :mypages, only: [:index]
    resources :favorites, only: [:index]
  end
  resources :posts, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  resources :contacts, only: [:new, :create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  resources :password_resets, only: [:new, :create, :edit, :update]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/arm_armor.rb
class ArmArmor < Armor
end

app/models/armor.rb
class Armor < ApplicationRecord
  has_many :posts

  validates :type, presence: true
  validates :name, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: true }
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
end

app/models/body_armor.rb
class BodyArmor < Armor
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/first_color.rb
class FirstColor < ApplicationRecord
  belongs_to :post, optional: true

  enum part: { head: 0, body: 1, arm: 2, waist: 3, foot: 4 }

  validates :hue, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 360 }
  validates :saturation, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  validates :value, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
end

app/models/foot_armor.rb
class FootArmor < Armor
end

app/models/head_armor.rb
class HeadArmor < Armor
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :first_colors, dependent: :destroy
  has_many :second_colors, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  accepts_nested_attributes_for :first_colors, :second_colors

  belongs_to :user
  belongs_to :head_armor, optional: true
  belongs_to :body_armor, optional: true
  belongs_to :arm_armor, optional: true
  belongs_to :waist_armor, optional: true
  belongs_to :foot_armor, optional: true

  validates :character_gender, presence: true
  # imageカラムのバリデーションをカスタムする
  # エラーメッセージの内容を変更したい(今のままでは不自然)
  validates :image, presence: true

  enum character_gender: { gentlemen: 0, lady: 1 }

  def armor_name(object)
    if object.nil?
      'なし'
    else
      object.name
    end
  end

  def armors
    [head_armor, body_armor, arm_armor, waist_armor, foot_armor]
  end

  # postが保存されると、colorsのpartにそれぞれ値をいれる
  def first_color_change_part
    first_colors.first.update(part: 'head')
    first_colors.second.update(part: 'body')
    first_colors.third.update(part: 'arm')
    first_colors.fourth.update(part: 'waist')
    first_colors.fifth.update(part: 'foot')
  end

  def second_color_change_part
    second_colors.first.update(part: 'head')
    second_colors.second.update(part: 'body')
    second_colors.third.update(part: 'arm')
    second_colors.fourth.update(part: 'waist')
    second_colors.fifth.update(part: 'foot')
  end

  # いいねの多い順で並び替える
  ransacker :likes_count do
    query = '(SELECT COUNT(likes.post_id) FROM likes where likes.post_id = posts.id GROUP BY likes.post_id)'
    Arel.sql(query)
  end

  # partを指定して、first_colorsを生成
  # def first_colors_build_specify_parts
  #   first_colors.build(part: 'head')
  #   first_colors.build(part: 'body')
  #   first_colors.build(part: 'arm')
  #   first_colors.build(part: 'waist')
  #   first_colors.build(part: 'foot')
  # end

  # partを指定して、second_colorsを生成
  # def second_colors_build_specify_parts
  #   second_colors.build(part: 'head')
  #   second_colors.build(part: 'body')
  #   second_colors.build(part: 'arm')
  #   second_colors.build(part: 'waist')
  #   second_colors.build(part: 'foot')
  # end
end

app/models/second_color.rb
class SecondColor < ApplicationRecord
  belongs_to :post, optional: true

  enum part: { head: 0, body: 1, arm: 2, waist: 3, foot: 4 }

  validates :hue, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 360 }
  validates :saturation, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  validates :value, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, uniqueness: true, allow_nil: true

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  enum role: { general: 0, admin: 1 }

  def own?(object)
    id == object.user_id
  end

  def like?(post)
    likes.where(post_id: post.id).exists?
  end
end

app/models/waist_armor.rb
class WaistArmor < Armor
end

app/helpers/armors_helper.rb
module ArmorsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_admin_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light
  .navbar-brand
    = link_to (t 'defaults.top'), admin_root_path, class: 'top-menu'

    = link_to (t 'defaults.post'), new_post_path, class: 'post-menu'

  button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarmenu" aria-controls="navbarmenu" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon

  #navbarmenu.collapse.navbar-collapse
    ul.navbar-nav.me-auto.mb-2.mb-lg-0
      li.nav-item
        b.nav-link href="#"
          = link_to (t 'defaults.user_show'), user_path(current_user), class: 'user-menu'
      li.nav-item
        b.nav-link href="#"
          = link_to (t 'defaults.mypage'), user_mypages_path(current_user), class: 'mypage-menu'
      li.nav-item
        b.nav-link href="#"
          = link_to (t 'defaults.favorite'), user_favorites_path(current_user), class: 'favorite-menu'
      li.nav-item
        b.nav-link href="#"
          = link_to (t 'defaults.logout'), logout_path, method: :delete, class: 'logout-menu'
      li.nav-item
        b.nav-link href="#"
          = link_to (t 'defaults.create_armor'), new_admin_armor_path, class: 'armor-menu'
      li.nav-item
        b.nav-link href="#"
          = link_to (t 'defaults.index_armor'), admin_armors_path, class: 'armor-menu'

app/views/shared/_before_login_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light
  .navbar-brand
    = link_to (t 'defaults.top'), root_path, class: 'top-menu'

  button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarmenu" aria-controls="navbarmenu" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon

  #navbarmenu.collapse.navbar-collapse
    ul.navbar-nav.me-auto.mb-2.mb-lg-0
      li.nav-item
        b.nav-link href="#"
          = link_to (t 'defaults.sign_up'), new_user_path, class: 'signup-menu'
      li.nav-item
        b.nav-link href="#"
          = link_to (t 'defaults.login'), login_path, class: 'login-menu'
      li.nav-item
        b.nav-link href="#"
          = link_to 'お知らせ', '#', class: 'notification-menu'

app/views/shared/_error_message.html.slim
- object.errors.any?
  - object.errors.full_messages.each do |msg|
    .text-center
      = msg
      br

app/views/shared/_flash_message.html.slim
- flash.each do |message_type, message|
  div class="alert alert-#{message_type}"
    = message

app/views/shared/_footer.html.slim
footer
  = link_to 'お問い合わせ', new_contact_path, class: 'contact-menu'
  = link_to '利用規約', static_pages_term_path, class: 'terms-menu'
  = link_to 'プライバシーポリシー', static_pages_privacy_path, class: 'privacy-menu'

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light
  .navbar-brand
    = link_to (t 'defaults.top'), root_path, class: 'top-menu'

    = link_to (t 'defaults.post'), new_post_path, class: 'post-menu'

  button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarmenu" aria-controls="navbarmenu" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon

  #navbarmenu.collapse.navbar-collapse
    ul.navbar-nav.me-auto.mb-2.mb-lg-0
      li.nav-item
        b.nav-link href="#"
          = link_to (t 'defaults.user_show'), user_path(current_user), class: 'user-menu'
      li.nav-item
        b.nav-link href="#"
          = link_to (t 'defaults.mypage'), user_mypages_path(current_user), class: 'mypage-menu'
      li.nav-item
        b.nav-link href="#"
          = link_to (t 'defaults.favorite'), user_favorites_path(current_user), class: 'favorite-menu'
      li.nav-item
        b.nav-link href="#"
          = link_to 'お知らせ', '#', class: 'notification-menu'
      li.nav-item
        b.nav-link href="#"
          = link_to (t 'defaults.logout'), logout_path, method: :delete, class: 'logout-menu'

app/views/shared/_search_form.html.slim
= search_form_for(q, url: url) do |f|

  = f.label :character_gender, class: 'mx-2'
  = f.select :character_gender_eq, Post.character_genders_i18n.invert.map{|k, v| [k, Post.character_genders[v]] }, include_blank: '指定なし'
  = f.label '並び順', class: 'mx-2'
  = f.select(:sorts, { 'ハートの多い順': 'likes_count desc', 'ハートの少ない順': 'likes_count asc', '新しい順': 'updated_at desc', '古い順': 'updated_at asc' }, { include_blank: '並び順' })
  = f.text_field :title_cont, placeholder: 'タイトルで検索', class: 'mx-2 mb-2'
  .field
    = f.text_field :head_armor_name_cont, placeholder: '頭部で検索', class: 'search-form'
    = f.text_field :body_armor_name_cont, placeholder: '胴部で検索', class: 'search-form'
    = f.text_field :arm_armor_name_cont, placeholder: '腕部で検索', class: 'search-form'
    = f.text_field :waist_armor_name_cont, placeholder: '腰部で検索', class: 'search-form'
    = f.text_field :foot_armor_name_cont, placeholder: '脚部で検索', class: 'search-form'
    
  .actions.text-center
    = f.submit

app/views/shared/_title_name.html.slim
.container-fluid
  h1.text-center
    .title-name = "モンスターハンターライズ"
  h1.text-center
    .title-name2 = "重ね着検索・共有"