config/routes.rb
Rails.application.routes.draw do
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider
  root 'static_pages#top'
  get 'static_pages/term'
  get 'static_pages/privacy'
  namespace :admin do
    root 'static_pages#top'
    resources :armors, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :users, only: [:destroy]
    resources :posts, only: [:destroy]
  end
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :mypages, only: [:index]
    resources :favorites, only: [:index]
  end
  resources :posts, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  resources :contacts, only: [:new, :create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  resources :password_resets, only: [:new, :create, :edit, :update]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :first_colors, dependent: :destroy
  has_many :second_colors, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  accepts_nested_attributes_for :first_colors, :second_colors

  belongs_to :user
  belongs_to :head_armor, optional: true
  belongs_to :body_armor, optional: true
  belongs_to :arm_armor, optional: true
  belongs_to :waist_armor, optional: true
  belongs_to :foot_armor, optional: true

  validates :character_gender, presence: true
  # imageカラムのバリデーションをカスタムする
  # エラーメッセージの内容を変更したい(今のままでは不自然)
  validates :image, presence: true

  enum character_gender: { gentlemen: 0, lady: 1 }

  def armor_name(object)
    if object.nil?
      'なし'
    else
      object.name
    end
  end

  def armors
    [head_armor, body_armor, arm_armor, waist_armor, foot_armor]
  end

  # postが保存されると、colorsのpartにそれぞれ値をいれる
  def first_color_change_part
    first_colors.first.update(part: 'head')
    first_colors.second.update(part: 'body')
    first_colors.third.update(part: 'arm')
    first_colors.fourth.update(part: 'waist')
    first_colors.fifth.update(part: 'foot')
  end

  def second_color_change_part
    second_colors.first.update(part: 'head')
    second_colors.second.update(part: 'body')
    second_colors.third.update(part: 'arm')
    second_colors.fourth.update(part: 'waist')
    second_colors.fifth.update(part: 'foot')
  end

  # いいねの多い順で並び替える
  ransacker :likes_count do
    query = '(SELECT COUNT(likes.post_id) FROM likes where likes.post_id = posts.id GROUP BY likes.post_id)'
    Arel.sql(query)
  end

  # partを指定して、first_colorsを生成
  # def first_colors_build_specify_parts
  #   first_colors.build(part: 'head')
  #   first_colors.build(part: 'body')
  #   first_colors.build(part: 'arm')
  #   first_colors.build(part: 'waist')
  #   first_colors.build(part: 'foot')
  # end

  # partを指定して、second_colorsを生成
  # def second_colors_build_specify_parts
  #   second_colors.build(part: 'head')
  #   second_colors.build(part: 'body')
  #   second_colors.build(part: 'arm')
  #   second_colors.build(part: 'waist')
  #   second_colors.build(part: 'foot')
  # end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::BaseController
    before_action :set_post, only: [:destroy]

    def destroy
      @post.destroy!
      redirect_to admin_root_path, success: (t '.success')
    end

    private

    def set_post
      @post = Post.find(params[:id])
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  skip_before_action :require_login, only: [:show]

  def index; end

  def show; end

  def new
    @post = Post.new
    5.times { @post.first_colors.build }
    5.times { @post.second_colors.build }
    # @post.first_colors_build_specify_parts
    # @post.second_colors_build_specify_parts
  end

  def create
    @post = current_user.posts.build(post_params)

    # postを保存したら、colorsのpartカラムに各々部位をいれる
    if @post.save
      @post.first_color_change_part
      @post.second_color_change_part
      redirect_to root_path, success: (t '.success')
    else
      flash.now[:danger] = t '.fail'
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(update_post_params)
      redirect_to post_path(@post), success: (t '.success')
    else
      flash.now[:fail] = t '.fail'
      render :edit
    end
  end

  def destroy
    @post.destroy!
    redirect_to root_path, success: (t '.success')
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :character_gender, :image, :image_cache, :head_armor_id,
                                 :body_armor_id, :arm_armor_id, :waist_armor_id, :foot_armor_id,
                                 first_colors_attributes: [:part, :hue, :saturation, :value, :post_id],
                                 second_colors_attributes: [:part, :hue, :saturation, :value, :post_id])
  end

  # colorsテーブルのidを追加 idの追加で、更新の度に入力欄が増加する現象を防止
  def update_post_params
    params.require(:post).permit(:title, :character_gender, :image, :image_cache, :head_armor_id,
                                 :body_armor_id, :arm_armor_id, :waist_armor_id, :foot_armor_id,
                                 first_colors_attributes: [:id, :part, :hue, :saturation, :value, :post_id],
                                 second_colors_attributes: [:id, :part, :hue, :saturation, :value, :post_id])
  end

  def correct_user
    @post = Post.find(params[:id])
    redirect_to root_path unless current_user.admin? || current_user == @post.user
  end
end

app/helpers/admin/posts_helper.rb
module Admin
  module PostsHelper
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
= form_with model: post, local: true do |f|

  = render 'shared/error_message', object: f.object

  .form-style
    .gender-field
      = f.label :character_gender
      = f.select :character_gender, Post.character_genders_i18n.keys.map{|k| [I18n.t("enums.post.character_gender.#{k}"), k]}
    .title-field
      = f.label :title
      = f.text_field :title, class: 'form-field'

  .top-image.text-center
    = f.label :image
    = f.file_field :image, accept: 'image/*', id: 'post_img'
    / バリデーションエラーになった場合でも、画像がアップロードしたままになる
    = f.hidden_field :image_cache
    / バリデーションエラーが発生した場合でも、画像が表示される
    / = image_tag post.image.url, size: "100x100" if post.image?
    
    / - if post.image?
    = image_tag post.image.url, size: '300x200', id: 'img_prev'
    / - else
      = image_tag 'goodstockphotos_eyecatch-480x302.jpeg', size: '100x100'

  .color-name-label
    h5.first-color-label
      = '着彩1'
      = '色相(H)'
      = '彩度(S)'
      = '明度(V)'
    h5.second-color-label
      = '着彩2'
      = '色相(H)'
      = '彩度(S)'
      = '明度(V)'

  .form-groups
    .form-armor
      .field.mb-1
        = f.label :head_armor_id
        = f.select :head_armor_id, HeadArmor.order(name: :asc).pluck(:name, :id), { prompt: '----' }, class: 'armor-field'
      .field.mb-1
        = f.label :body_armor_id
        = f.select :body_armor_id, BodyArmor.order(name: :asc).pluck(:name, :id), { prompt: '----' }, class: 'armor-field'
      .field.mb-1
        = f.label :arm_armor_id
        = f.select :arm_armor_id, ArmArmor.order(name: :asc).pluck(:name, :id), { prompt: '----' }, class: 'armor-field'
      .field.mb-1
        = f.label :waist_armor_id
        = f.select :waist_armor_id, WaistArmor.order(name: :asc).pluck(:name, :id), { prompt: '----' }, class: 'armor-field'
      .field.mb-1
        = f.label :foot_armor_id
        = f.select :foot_armor_id, FootArmor.order(name: :asc).pluck(:name, :id), { prompt: '----' }, class: 'armor-field'

    .first-color-form
      = f.fields_for :first_colors do |ff|
        .color-fields
          .color-field
            /= ff.label :hue
            = ff.number_field :hue, { max: 360 }
          .color-field
            /= ff.label :saturation
            = ff.number_field :saturation, { max: 100 }
          .color-field
            /= ff.label :value
            = ff.number_field :value, { max: 100 }

    .second-color-form
      = f.fields_for :second_colors do |fff|
        .color-fields
          .color-field
            /= fff.label :hue
            = fff.number_field :hue, { max: 360 }
          .color-field
            /= fff.label :saturation
            = fff.number_field :saturation, { max: 100 }
          .color-field
            /= fff.label :value
            = fff.number_field :value, { max: 100 }

  .actions.text-center.mt-5
    = f.submit button_name

app/views/posts/_like.html.slim
= link_to post_likes_path(post), method: :post, id: "js-like-button-#{post.id}", remote: true do
  .likes-button
    = icon 'far', 'heart'
    = post.likes.count

app/views/posts/_like_area.html.slim
- if current_user.like?(post)
  = render 'posts/unlike', post: post, like: like
- else
  = render 'posts/like', post: post

app/views/posts/_post.html.slim
.card
  .card-body
    h5.card-title
      = link_to "#{post.title}", post_path(post), class: 'post-title'
      - if logged_in?
        = render 'posts/like_area', post: post, like: like


  .card-img-bottom
    - if post.image?
      = link_to image_tag(post.image_url, size: '300x200'), post_path(post), class: 'post_image'

app/views/posts/_unlike.html.slim
= link_to post_like_path(post, [post, like]), id: "js-like-button-#{post.id}", remote: true , method: :delete do
  .likes-button
    = icon 'fas', 'heart'
    = post.likes.count

app/views/posts/edit.html.slim
- provide :title, (t '.title')

h3.text-center.mb-3
  = t '.title'

= render 'form', post: @post, button_name: (t 'defaults.update')

app/views/posts/new.html.slim
- provide :title, (t '.title')

h3.text-center.mb-3
  = t '.title'

= render 'form', post: @post, button_name: (t 'defaults.post')

app/views/posts/show.html.slim
- provide :title, (t '.title')

h3.text-center
  = t '.title'

table
  thead
    tr
      th
        = "タイトル"
      th
        = "重ね着画像"
      th
        = "キャラの性別"
      th
        = "ユーザー名"

  tbody
    tr
      td
        = @post.title
      td
        - if @post.image?
          = image_tag @post.image_url, size: '300x200'
      td
        = @post.character_gender_i18n
      td
        = @post.user.name
.post-show
  table.armors style="display: flex;" align="left"
    thead
      tr style="display: block;"
        th style="display: block;"
          = "頭"
        th style=" display: block;"
          = "胴"
        th style=" display: block;"
          = "腕"
        th style=" display: block;"
          = "腰"
        th style=" display: block;"
          = "脚"
    tbody
      tr style=" display: block;"
      - @post.armors.each do |armor|
        td style=" display: block;"
          - if armor.nil?
            = 'なし'
          - else
            = armor.name

  table.first-color
    thead
      tr 
        th
          = "色相(H)"
        th
          = "彩度(S)"
        th
          = "明度(V)"


    tbody
      - @post.first_colors.each do |color|
        tr
          td
            = color.hue
          td
            = color.saturation
          td
            = color.value

  table.second-color
    thead
      tr 
        th
          = "色相(H)"
        th
          = "彩度(S)"
        th
          = "明度(V)"


    tbody
      - @post.second_colors.each do |color|
        tr
          td
            = color.hue
          td
            = color.saturation
          td
            = color.value

.link-menu
  - if current_user && current_user == @post.user
    = link_to (t '.edit'), edit_post_path(@post), class: 'edit-link mx-2'
    = link_to (t '.destroy'), post_path(@post), method: :delete, data: { confirm: (t '.dialog') }, class: 'destroy-link'
= link_to "http://twitter.com/intent/tweet?url=#{ request.url }/&hashtags=モンハンライズ%2C重ね着 を、Twitterでみんなに広めよう" do
        i.fab.fa-twitter style='color: #3399FF;'
        |  共有