config/routes.rb
Rails.application.routes.draw do
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider
  root 'static_pages#top'
  get 'static_pages/term'
  get 'static_pages/privacy'
  namespace :admin do
    root 'static_pages#top'
    resources :armors, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :users, only: [:destroy]
    resources :posts, only: [:destroy]
  end
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :mypages, only: [:index]
    resources :favorites, only: [:index]
  end
  resources :posts, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  resources :contacts, only: [:new, :create]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  resources :password_resets, only: [:new, :create, :edit, :update]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/armor.rb
class Armor < ApplicationRecord
  has_many :posts

  validates :type, presence: true
  validates :name, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: true }
end

app/controllers/admin/armors_controller.rb
module Admin
  class ArmorsController < Admin::BaseController
    before_action :set_armor, only: [:edit, :update, :destroy]

    def index
      @head_armors = HeadArmor.all
      @body_armors = BodyArmor.all
      @arm_armors = ArmArmor.all
      @waist_armors = WaistArmor.all
      @foot_armors = FootArmor.all
    end

    def new
      @armor = Armor.new
    end

    def create
      @armor = Armor.new(armor_params)
      if @armor.save
        redirect_to new_admin_armor_path, success: @armor.attributes.to_s
      else
        redirect_to new_admin_armor_path, danger: '装備の作成に失敗しました。'
      end
    end

    def edit; end

    def update
      case @armor.type
      when 'HeadArmor'
        @armor.assign_attributes(head_armor_params)
      when 'BodyArmor'
        @armor.assign_attributes(body_armor_params)
      when 'ArmArmor'
        @armor.assign_attributes(arm_armor_params)
      when 'WaistArmor'
        @armor.assign_attributes(waist_armor_params)
      when 'FootArmor'
        @armor.assign_attributes(foot_armor_params)
      end
      if @armor.save
        redirect_to admin_armors_path, success: '装備を更新しました。'
      else
        flash.now[:danger] = '装備の更新に失敗しました。'
        render :edit
      end
    end

    def destroy
      @armor.destroy!
      redirect_to admin_armors_path, success: '装備を削除しました。'
    end

    private

    def set_armor
      @armor = Armor.find(params[:id])
    end

    def armor_params
      params.require(:armor).permit(:type, :name)
    end

    def head_armor_params
      params.require(:head_armor).permit(:type, :name)
    end

    def body_armor_params
      params.require(:body_armor).permit(:type, :name)
    end

    def arm_armor_params
      params.require(:arm_armor).permit(:type, :name)
    end

    def waist_armor_params
      params.require(:waist_armor).permit(:type, :name)
    end

    def foot_armor_params
      params.require(:foot_armor).permit(:type, :name)
    end
  end
end

app/controllers/armors_controller.rb
class ArmorsController < ApplicationController
  before_action :check_admin
  before_action :set_armor, only: [:edit, :update, :destroy]
  
  def index
    @head_armors = HeadArmor.all
    @body_armors = BodyArmor.all
    @arm_armors = ArmArmor.all
    @waist_armors = WaistArmor.all
    @foot_armors = FootArmor.all
  end

  def new
    @armor = Armor.new
  end

  def create
    @armor = Armor.new(armor_params)
    if @armor.save
      redirect_to new_armor_path, success: "#{@armor.attributes}"
    else
      redirect_to new_armor_path, danger: '装備の作成に失敗しました。'
    end
  end

  def edit; end

  def update
    case @armor.type
    when 'HeadArmor'
      @armor.assign_attributes(head_armor_params)
    when 'BodyArmor'
      @armor.assign_attributes(body_armor_params)
    when 'ArmArmor'
      @armor.assign_attributes(arm_armor_params)
    when 'WaistArmor'
      @armor.assign_attributes(waist_armor_params)
    when 'FootArmor'
      @armor.assign_attributes(foot_armor_params)
    end
    if @armor.save
      redirect_to armors_path, success: '装備を更新しました。'
    else
      flash.now[:danger] = '装備の更新に失敗しました。'
      render :edit
    end
  end

  def destroy
    @armor.destroy!
    redirect_to armors_path, success: '装備を削除しました。'
  end


  private

  def set_armor
    @armor = Armor.find(params[:id])
  end

  def armor_params
    params.require(:armor).permit(:type, :name)
  end

  def head_armor_params
    params.require(:head_armor).permit(:type, :name)
  end

  def body_armor_params
    params.require(:body_armor).permit(:type, :name)
  end

  def arm_armor_params
    params.require(:arm_armor).permit(:type, :name)
  end

  def waist_armor_params
    params.require(:waist_armor).permit(:type, :name)
  end

  def foot_armor_params
    params.require(:foot_armor).permit(:type, :name)
  end

  def check_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/helpers/admin/armors_helper.rb
module Admin
  module ArmorsHelper
  end
end

app/helpers/armors_helper.rb
module ArmorsHelper
end

app/views/admin/armors/_form.html.slim
= form_with model: armor, url: url, local: true do |f|

  .mx-auto
    .field.mb-3
      = f.label :type
      = f.select :type, { 頭: 'HeadArmor', 胴: 'BodyArmor', 腕: 'ArmArmor', 腰: 'WaistArmor', 脚: 'FootArmor' }

    .field
      = f.label :name
      = f.text_field :name, class: 'form-field'

    .actions.text-center.mt-3
      = f.submit button_name

app/views/admin/armors/edit.html.slim
- provide :title, (t '.title')

h3.text-center.mb-3
  = t '.title'

= render 'form', armor: @armor, url: admin_armor_path, button_name: (t 'defaults.update')

app/views/admin/armors/index.html.slim
- provide :title, (t '.title')

h3.text-center.mb-3
  = t '.title'

- if @head_armors.present?
  h5
    = HeadArmor.human_attribute_name(:type)
    = HeadArmor.count
  = render @head_armors

- if @body_armors.present?
  h5
    = BodyArmor.human_attribute_name(:type)
    = BodyArmor.count
  = render @body_armors

- if @arm_armors.present?
  h5
    = ArmArmor.human_attribute_name(:type)
    = ArmArmor.count
  = render @arm_armors

- if @waist_armors.present?
  h5
    = WaistArmor.human_attribute_name(:type)
    = WaistArmor.count
  = render @waist_armors

- if @foot_armors.present?
  h5
    = FootArmor.human_attribute_name(:type)
    = FootArmor.count
  = render @foot_armors

app/views/admin/armors/new.html.slim
- provide :title, (t '.title')

h3.text-center.mb-3
  = t '.title'

= render 'form', armor: @armor, url: admin_armors_path, button_name: (t 'defaults.create')